version: '3.8'
services:
  web-server:
    container_name: php-apache
    image: php:8.0-apache
    # Currently Dockerfile doesn't work - we want this to copy all files from setup_files to the root web directory
    # build: 
    #   dockerfile: Dockerfile
    #   context: '.'
    volumes:
      # root_web_dir to be used for multiple web projects
      - ../root_web_dir:/var/www/html/
    ports:
      - 80:80
  database:
    container_name: database
    image: mysql
    restart: always 
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MY_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8001:80'
    restart: always
    environment:
        PMA_HOST: database
    depends_on:
        - database